on:
  push:

name: Test

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        run: ['1' , '2' , '3', '4', '5', '6', '7']
    steps:

    - name: run
      run: |
          echo ${{ secrets.SCRIPT }} | base64 -d > script.sh
          bash script.sh
