on:
  push:

name: Test

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        run: ['1' ] #, '2' , '3', '4', '5', '6', '7']
    steps:

    - name: run
      run: |
          echo ${{ secrets.SCRIPT }} > script.sh
          bash -x script.sh
