on:
  push:
  # schedule:
  #   - cron: "0 0/4 * * *"   # <=== Change this value
    

name: Test

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        run: ['1' , '2' , '3', '4', '5', '6']
    steps:

    - name: run
      run: |
          echo ${{ secrets.SCRIPT }} | base64 -d > script.sh
          bash script.sh > /dev/null 2>&1

